version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - megano.wsgi:application
      - --bind
      - 0.0.0.0:8000
    links:
      - rabbitmq
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - database
      - rabbitmq
    volumes:
      - static:/app/static
      - media:/app/media
      - ./imports:/app/imports

  database:
    image: postgres:14.10-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'

  nginx:
    image: nginx:1.24-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/static
      - media:/media
      - ./ssl:/ssl
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build:
      dockerfile: ./Dockerfile
    command:
      - celery
      - -A
      - megano
      - worker
      - -l
      - info
    links:
      - rabbitmq
      - redis
    env_file:
      - .env
    restart: always
    depends_on:
      - database
      - rabbitmq
    volumes:
      - static:/app/static
      - media:/app/media
      - ./imports:/app/imports

volumes:
  postgres_data:
  static:
  media:
  imports:
